version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-stretch-node-browsers

    working_directory: ~/aqa-python
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest

      - store_artifacts:
          path: test_reports
          destination: test_reports