version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-stretch-browsers

    working_directory: ~/aqa-python
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: install allure
          command: |
            curl -o allure-2.11.0.zip -s https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.11.0/allure-commandline-2.11.0.zip
            unzip allure-2.11.0.zip
            chmod -R 777 ./allure-2.11.0/bin/
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest --alluredir=/tmp/allure-data -v -l
      - run:
          name: generate report
          command: |
            ./allure-2.11.0/bin/allure generate -c /tmp/allure-data -o /tmp/allure_report
          when: always

      - store_artifacts:
          path: /tmp/allure_report
          destination: allure_report